// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: audio_separation.proto

package audiosep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_CREATED    Status = 0
	Status_PENDING    Status = 1
	Status_PROCESSING Status = 2
	Status_DONE       Status = 3
	Status_FAILED     Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CREATED",
		1: "PENDING",
		2: "PROCESSING",
		3: "DONE",
		4: "FAILED",
	}
	Status_value = map[string]int32{
		"CREATED":    0,
		"PENDING":    1,
		"PROCESSING": 2,
		"DONE":       3,
		"FAILED":     4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_separation_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_audio_separation_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{0}
}

type AudioSepTask struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=audio_sep.Status" json:"status,omitempty"`
	InputAudioName   string                 `protobuf:"bytes,3,opt,name=input_audio_name,json=inputAudioName,proto3" json:"input_audio_name,omitempty"`
	SeparatedDirName string                 `protobuf:"bytes,4,opt,name=separated_dir_name,json=separatedDirName,proto3" json:"separated_dir_name,omitempty"`
	StemsUrls        map[string]string      `protobuf:"bytes,5,rep,name=stems_urls,json=stemsUrls,proto3" json:"stems_urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorMessage     *string                `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AudioSepTask) Reset() {
	*x = AudioSepTask{}
	mi := &file_audio_separation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioSepTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSepTask) ProtoMessage() {}

func (x *AudioSepTask) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSepTask.ProtoReflect.Descriptor instead.
func (*AudioSepTask) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{0}
}

func (x *AudioSepTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioSepTask) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

func (x *AudioSepTask) GetInputAudioName() string {
	if x != nil {
		return x.InputAudioName
	}
	return ""
}

func (x *AudioSepTask) GetSeparatedDirName() string {
	if x != nil {
		return x.SeparatedDirName
	}
	return ""
}

func (x *AudioSepTask) GetStemsUrls() map[string]string {
	if x != nil {
		return x.StemsUrls
	}
	return nil
}

func (x *AudioSepTask) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type PostAudioSepTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAudioSepTaskRequest) Reset() {
	*x = PostAudioSepTaskRequest{}
	mi := &file_audio_separation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAudioSepTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAudioSepTaskRequest) ProtoMessage() {}

func (x *PostAudioSepTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAudioSepTaskRequest.ProtoReflect.Descriptor instead.
func (*PostAudioSepTaskRequest) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{1}
}

func (x *PostAudioSepTaskRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PostAudioSepTaskRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PostAudioSepTaskRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PostAudioSepTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *AudioSepTask          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAudioSepTaskResponse) Reset() {
	*x = PostAudioSepTaskResponse{}
	mi := &file_audio_separation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAudioSepTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAudioSepTaskResponse) ProtoMessage() {}

func (x *PostAudioSepTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAudioSepTaskResponse.ProtoReflect.Descriptor instead.
func (*PostAudioSepTaskResponse) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{2}
}

func (x *PostAudioSepTaskResponse) GetTask() *AudioSepTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetAudioSepTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioSepTaskRequest) Reset() {
	*x = GetAudioSepTaskRequest{}
	mi := &file_audio_separation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioSepTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioSepTaskRequest) ProtoMessage() {}

func (x *GetAudioSepTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioSepTaskRequest.ProtoReflect.Descriptor instead.
func (*GetAudioSepTaskRequest) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{3}
}

func (x *GetAudioSepTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAudioSepTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *AudioSepTask          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioSepTaskResponse) Reset() {
	*x = GetAudioSepTaskResponse{}
	mi := &file_audio_separation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioSepTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioSepTaskResponse) ProtoMessage() {}

func (x *GetAudioSepTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioSepTaskResponse.ProtoReflect.Descriptor instead.
func (*GetAudioSepTaskResponse) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{4}
}

func (x *GetAudioSepTaskResponse) GetTask() *AudioSepTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type UploadStemsURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	StemsNames    []string               `protobuf:"bytes,3,rep,name=stems_names,json=stemsNames,proto3" json:"stems_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStemsURLsRequest) Reset() {
	*x = UploadStemsURLsRequest{}
	mi := &file_audio_separation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStemsURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStemsURLsRequest) ProtoMessage() {}

func (x *UploadStemsURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStemsURLsRequest.ProtoReflect.Descriptor instead.
func (*UploadStemsURLsRequest) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{5}
}

func (x *UploadStemsURLsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadStemsURLsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UploadStemsURLsRequest) GetStemsNames() []string {
	if x != nil {
		return x.StemsNames
	}
	return nil
}

type UploadStemsURLsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StemsUploadUrls map[string]string      `protobuf:"bytes,1,rep,name=stems_upload_urls,json=stemsUploadUrls,proto3" json:"stems_upload_urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadStemsURLsResponse) Reset() {
	*x = UploadStemsURLsResponse{}
	mi := &file_audio_separation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStemsURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStemsURLsResponse) ProtoMessage() {}

func (x *UploadStemsURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStemsURLsResponse.ProtoReflect.Descriptor instead.
func (*UploadStemsURLsResponse) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{6}
}

func (x *UploadStemsURLsResponse) GetStemsUploadUrls() map[string]string {
	if x != nil {
		return x.StemsUploadUrls
	}
	return nil
}

type TryUpdateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusFrom Status                 `protobuf:"varint,2,opt,name=status_from,json=statusFrom,proto3,enum=audio_sep.Status" json:"status_from,omitempty"`
	StatusTo   Status                 `protobuf:"varint,3,opt,name=status_to,json=statusTo,proto3,enum=audio_sep.Status" json:"status_to,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TryUpdateRequest_ProcessingData
	//	*TryUpdateRequest_DoneData
	//	*TryUpdateRequest_ErrorData
	Payload       isTryUpdateRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryUpdateRequest) Reset() {
	*x = TryUpdateRequest{}
	mi := &file_audio_separation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUpdateRequest) ProtoMessage() {}

func (x *TryUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUpdateRequest.ProtoReflect.Descriptor instead.
func (*TryUpdateRequest) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{7}
}

func (x *TryUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TryUpdateRequest) GetStatusFrom() Status {
	if x != nil {
		return x.StatusFrom
	}
	return Status_CREATED
}

func (x *TryUpdateRequest) GetStatusTo() Status {
	if x != nil {
		return x.StatusTo
	}
	return Status_CREATED
}

func (x *TryUpdateRequest) GetPayload() isTryUpdateRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TryUpdateRequest) GetProcessingData() *ProcessingData {
	if x != nil {
		if x, ok := x.Payload.(*TryUpdateRequest_ProcessingData); ok {
			return x.ProcessingData
		}
	}
	return nil
}

func (x *TryUpdateRequest) GetDoneData() *DoneData {
	if x != nil {
		if x, ok := x.Payload.(*TryUpdateRequest_DoneData); ok {
			return x.DoneData
		}
	}
	return nil
}

func (x *TryUpdateRequest) GetErrorData() *ErrorData {
	if x != nil {
		if x, ok := x.Payload.(*TryUpdateRequest_ErrorData); ok {
			return x.ErrorData
		}
	}
	return nil
}

type isTryUpdateRequest_Payload interface {
	isTryUpdateRequest_Payload()
}

type TryUpdateRequest_ProcessingData struct {
	ProcessingData *ProcessingData `protobuf:"bytes,4,opt,name=processing_data,json=processingData,proto3,oneof"`
}

type TryUpdateRequest_DoneData struct {
	DoneData *DoneData `protobuf:"bytes,5,opt,name=done_data,json=doneData,proto3,oneof"`
}

type TryUpdateRequest_ErrorData struct {
	ErrorData *ErrorData `protobuf:"bytes,6,opt,name=error_data,json=errorData,proto3,oneof"`
}

func (*TryUpdateRequest_ProcessingData) isTryUpdateRequest_Payload() {}

func (*TryUpdateRequest_DoneData) isTryUpdateRequest_Payload() {}

func (*TryUpdateRequest_ErrorData) isTryUpdateRequest_Payload() {}

type ProcessingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingData) Reset() {
	*x = ProcessingData{}
	mi := &file_audio_separation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingData) ProtoMessage() {}

func (x *ProcessingData) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingData.ProtoReflect.Descriptor instead.
func (*ProcessingData) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{8}
}

type DoneData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeparatedDirName string                 `protobuf:"bytes,1,opt,name=separated_dir_name,json=separatedDirName,proto3" json:"separated_dir_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DoneData) Reset() {
	*x = DoneData{}
	mi := &file_audio_separation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneData) ProtoMessage() {}

func (x *DoneData) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneData.ProtoReflect.Descriptor instead.
func (*DoneData) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{9}
}

func (x *DoneData) GetSeparatedDirName() string {
	if x != nil {
		return x.SeparatedDirName
	}
	return ""
}

type ErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_audio_separation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorData) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TryUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryUpdateResponse) Reset() {
	*x = TryUpdateResponse{}
	mi := &file_audio_separation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUpdateResponse) ProtoMessage() {}

func (x *TryUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_separation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUpdateResponse.ProtoReflect.Descriptor instead.
func (*TryUpdateResponse) Descriptor() ([]byte, []int) {
	return file_audio_separation_proto_rawDescGZIP(), []int{11}
}

func (x *TryUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_audio_separation_proto protoreflect.FileDescriptor

const file_audio_separation_proto_rawDesc = "" +
	"\n" +
	"\x16audio_separation.proto\x12\taudio_sep\"\xe2\x02\n" +
	"\fAudioSepTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.audio_sep.StatusR\x06status\x12(\n" +
	"\x10input_audio_name\x18\x03 \x01(\tR\x0einputAudioName\x12,\n" +
	"\x12separated_dir_name\x18\x04 \x01(\tR\x10separatedDirName\x12E\n" +
	"\n" +
	"stems_urls\x18\x05 \x03(\v2&.audio_sep.AudioSepTask.StemsUrlsEntryR\tstemsUrls\x12(\n" +
	"\rerror_message\x18\x06 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x1a<\n" +
	"\x0eStemsUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_error_message\"^\n" +
	"\x17PostAudioSepTaskRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"G\n" +
	"\x18PostAudioSepTaskResponse\x12+\n" +
	"\x04task\x18\x01 \x01(\v2\x17.audio_sep.AudioSepTaskR\x04task\"(\n" +
	"\x16GetAudioSepTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x17GetAudioSepTaskResponse\x12+\n" +
	"\x04task\x18\x01 \x01(\v2\x17.audio_sep.AudioSepTaskR\x04task\"a\n" +
	"\x16UploadStemsURLsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1f\n" +
	"\vstems_names\x18\x03 \x03(\tR\n" +
	"stemsNames\"\xc2\x01\n" +
	"\x17UploadStemsURLsResponse\x12c\n" +
	"\x11stems_upload_urls\x18\x01 \x03(\v27.audio_sep.UploadStemsURLsResponse.StemsUploadUrlsEntryR\x0fstemsUploadUrls\x1aB\n" +
	"\x14StemsUploadUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\x10TryUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\vstatus_from\x18\x02 \x01(\x0e2\x11.audio_sep.StatusR\n" +
	"statusFrom\x12.\n" +
	"\tstatus_to\x18\x03 \x01(\x0e2\x11.audio_sep.StatusR\bstatusTo\x12D\n" +
	"\x0fprocessing_data\x18\x04 \x01(\v2\x19.audio_sep.ProcessingDataH\x00R\x0eprocessingData\x122\n" +
	"\tdone_data\x18\x05 \x01(\v2\x13.audio_sep.DoneDataH\x00R\bdoneData\x125\n" +
	"\n" +
	"error_data\x18\x06 \x01(\v2\x14.audio_sep.ErrorDataH\x00R\terrorDataB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eProcessingData\"8\n" +
	"\bDoneData\x12,\n" +
	"\x12separated_dir_name\x18\x01 \x01(\tR\x10separatedDirName\"0\n" +
	"\tErrorData\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"-\n" +
	"\x11TryUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*H\n" +
	"\x06Status\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\b\n" +
	"\x04DONE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xee\x02\n" +
	"\x13AudioSepTaskService\x12[\n" +
	"\x10PostAudioSepTask\x12\".audio_sep.PostAudioSepTaskRequest\x1a#.audio_sep.PostAudioSepTaskResponse\x12X\n" +
	"\x0fGetAudioSepTask\x12!.audio_sep.GetAudioSepTaskRequest\x1a\".audio_sep.GetAudioSepTaskResponse\x12X\n" +
	"\x0fUploadStemsURLs\x12!.audio_sep.UploadStemsURLsRequest\x1a\".audio_sep.UploadStemsURLsResponse\x12F\n" +
	"\tTryUpdate\x12\x1b.audio_sep.TryUpdateRequest\x1a\x1c.audio_sep.TryUpdateResponseB\vZ\t/audiosepb\x06proto3"

var (
	file_audio_separation_proto_rawDescOnce sync.Once
	file_audio_separation_proto_rawDescData []byte
)

func file_audio_separation_proto_rawDescGZIP() []byte {
	file_audio_separation_proto_rawDescOnce.Do(func() {
		file_audio_separation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_separation_proto_rawDesc), len(file_audio_separation_proto_rawDesc)))
	})
	return file_audio_separation_proto_rawDescData
}

var file_audio_separation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_audio_separation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_audio_separation_proto_goTypes = []any{
	(Status)(0),                      // 0: audio_sep.Status
	(*AudioSepTask)(nil),             // 1: audio_sep.AudioSepTask
	(*PostAudioSepTaskRequest)(nil),  // 2: audio_sep.PostAudioSepTaskRequest
	(*PostAudioSepTaskResponse)(nil), // 3: audio_sep.PostAudioSepTaskResponse
	(*GetAudioSepTaskRequest)(nil),   // 4: audio_sep.GetAudioSepTaskRequest
	(*GetAudioSepTaskResponse)(nil),  // 5: audio_sep.GetAudioSepTaskResponse
	(*UploadStemsURLsRequest)(nil),   // 6: audio_sep.UploadStemsURLsRequest
	(*UploadStemsURLsResponse)(nil),  // 7: audio_sep.UploadStemsURLsResponse
	(*TryUpdateRequest)(nil),         // 8: audio_sep.TryUpdateRequest
	(*ProcessingData)(nil),           // 9: audio_sep.ProcessingData
	(*DoneData)(nil),                 // 10: audio_sep.DoneData
	(*ErrorData)(nil),                // 11: audio_sep.ErrorData
	(*TryUpdateResponse)(nil),        // 12: audio_sep.TryUpdateResponse
	nil,                              // 13: audio_sep.AudioSepTask.StemsUrlsEntry
	nil,                              // 14: audio_sep.UploadStemsURLsResponse.StemsUploadUrlsEntry
}
var file_audio_separation_proto_depIdxs = []int32{
	0,  // 0: audio_sep.AudioSepTask.status:type_name -> audio_sep.Status
	13, // 1: audio_sep.AudioSepTask.stems_urls:type_name -> audio_sep.AudioSepTask.StemsUrlsEntry
	1,  // 2: audio_sep.PostAudioSepTaskResponse.task:type_name -> audio_sep.AudioSepTask
	1,  // 3: audio_sep.GetAudioSepTaskResponse.task:type_name -> audio_sep.AudioSepTask
	14, // 4: audio_sep.UploadStemsURLsResponse.stems_upload_urls:type_name -> audio_sep.UploadStemsURLsResponse.StemsUploadUrlsEntry
	0,  // 5: audio_sep.TryUpdateRequest.status_from:type_name -> audio_sep.Status
	0,  // 6: audio_sep.TryUpdateRequest.status_to:type_name -> audio_sep.Status
	9,  // 7: audio_sep.TryUpdateRequest.processing_data:type_name -> audio_sep.ProcessingData
	10, // 8: audio_sep.TryUpdateRequest.done_data:type_name -> audio_sep.DoneData
	11, // 9: audio_sep.TryUpdateRequest.error_data:type_name -> audio_sep.ErrorData
	2,  // 10: audio_sep.AudioSepTaskService.PostAudioSepTask:input_type -> audio_sep.PostAudioSepTaskRequest
	4,  // 11: audio_sep.AudioSepTaskService.GetAudioSepTask:input_type -> audio_sep.GetAudioSepTaskRequest
	6,  // 12: audio_sep.AudioSepTaskService.UploadStemsURLs:input_type -> audio_sep.UploadStemsURLsRequest
	8,  // 13: audio_sep.AudioSepTaskService.TryUpdate:input_type -> audio_sep.TryUpdateRequest
	3,  // 14: audio_sep.AudioSepTaskService.PostAudioSepTask:output_type -> audio_sep.PostAudioSepTaskResponse
	5,  // 15: audio_sep.AudioSepTaskService.GetAudioSepTask:output_type -> audio_sep.GetAudioSepTaskResponse
	7,  // 16: audio_sep.AudioSepTaskService.UploadStemsURLs:output_type -> audio_sep.UploadStemsURLsResponse
	12, // 17: audio_sep.AudioSepTaskService.TryUpdate:output_type -> audio_sep.TryUpdateResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_audio_separation_proto_init() }
func file_audio_separation_proto_init() {
	if File_audio_separation_proto != nil {
		return
	}
	file_audio_separation_proto_msgTypes[0].OneofWrappers = []any{}
	file_audio_separation_proto_msgTypes[7].OneofWrappers = []any{
		(*TryUpdateRequest_ProcessingData)(nil),
		(*TryUpdateRequest_DoneData)(nil),
		(*TryUpdateRequest_ErrorData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_separation_proto_rawDesc), len(file_audio_separation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_separation_proto_goTypes,
		DependencyIndexes: file_audio_separation_proto_depIdxs,
		EnumInfos:         file_audio_separation_proto_enumTypes,
		MessageInfos:      file_audio_separation_proto_msgTypes,
	}.Build()
	File_audio_separation_proto = out.File
	file_audio_separation_proto_goTypes = nil
	file_audio_separation_proto_depIdxs = nil
}
