// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: audio_separation.proto

package audiosep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioSepTaskService_PostAudioSepTask_FullMethodName = "/audio_sep.AudioSepTaskService/PostAudioSepTask"
	AudioSepTaskService_GetAudioSepTask_FullMethodName  = "/audio_sep.AudioSepTaskService/GetAudioSepTask"
	AudioSepTaskService_UploadStemsURLs_FullMethodName  = "/audio_sep.AudioSepTaskService/UploadStemsURLs"
	AudioSepTaskService_TryUpdate_FullMethodName        = "/audio_sep.AudioSepTaskService/TryUpdate"
)

// AudioSepTaskServiceClient is the client API for AudioSepTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AudioSepTaskService is the service for audio separation tasks.
type AudioSepTaskServiceClient interface {
	// PostAudioSepTask posts an audio separation task.
	PostAudioSepTask(ctx context.Context, in *PostAudioSepTaskRequest, opts ...grpc.CallOption) (*PostAudioSepTaskResponse, error)
	// GetAudioSepTask gets an audio separation task.
	GetAudioSepTask(ctx context.Context, in *GetAudioSepTaskRequest, opts ...grpc.CallOption) (*GetAudioSepTaskResponse, error)
	// UploadStemsURLs returns URLs for uploads stems.
	UploadStemsURLs(ctx context.Context, in *UploadStemsURLsRequest, opts ...grpc.CallOption) (*UploadStemsURLsResponse, error)
	// TryUpdate tries to update the task.
	TryUpdate(ctx context.Context, in *TryUpdateRequest, opts ...grpc.CallOption) (*TryUpdateResponse, error)
}

type audioSepTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioSepTaskServiceClient(cc grpc.ClientConnInterface) AudioSepTaskServiceClient {
	return &audioSepTaskServiceClient{cc}
}

func (c *audioSepTaskServiceClient) PostAudioSepTask(ctx context.Context, in *PostAudioSepTaskRequest, opts ...grpc.CallOption) (*PostAudioSepTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostAudioSepTaskResponse)
	err := c.cc.Invoke(ctx, AudioSepTaskService_PostAudioSepTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioSepTaskServiceClient) GetAudioSepTask(ctx context.Context, in *GetAudioSepTaskRequest, opts ...grpc.CallOption) (*GetAudioSepTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudioSepTaskResponse)
	err := c.cc.Invoke(ctx, AudioSepTaskService_GetAudioSepTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioSepTaskServiceClient) UploadStemsURLs(ctx context.Context, in *UploadStemsURLsRequest, opts ...grpc.CallOption) (*UploadStemsURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadStemsURLsResponse)
	err := c.cc.Invoke(ctx, AudioSepTaskService_UploadStemsURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioSepTaskServiceClient) TryUpdate(ctx context.Context, in *TryUpdateRequest, opts ...grpc.CallOption) (*TryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryUpdateResponse)
	err := c.cc.Invoke(ctx, AudioSepTaskService_TryUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioSepTaskServiceServer is the server API for AudioSepTaskService service.
// All implementations must embed UnimplementedAudioSepTaskServiceServer
// for forward compatibility.
//
// AudioSepTaskService is the service for audio separation tasks.
type AudioSepTaskServiceServer interface {
	// PostAudioSepTask posts an audio separation task.
	PostAudioSepTask(context.Context, *PostAudioSepTaskRequest) (*PostAudioSepTaskResponse, error)
	// GetAudioSepTask gets an audio separation task.
	GetAudioSepTask(context.Context, *GetAudioSepTaskRequest) (*GetAudioSepTaskResponse, error)
	// UploadStemsURLs returns URLs for uploads stems.
	UploadStemsURLs(context.Context, *UploadStemsURLsRequest) (*UploadStemsURLsResponse, error)
	// TryUpdate tries to update the task.
	TryUpdate(context.Context, *TryUpdateRequest) (*TryUpdateResponse, error)
	mustEmbedUnimplementedAudioSepTaskServiceServer()
}

// UnimplementedAudioSepTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioSepTaskServiceServer struct{}

func (UnimplementedAudioSepTaskServiceServer) PostAudioSepTask(context.Context, *PostAudioSepTaskRequest) (*PostAudioSepTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAudioSepTask not implemented")
}
func (UnimplementedAudioSepTaskServiceServer) GetAudioSepTask(context.Context, *GetAudioSepTaskRequest) (*GetAudioSepTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioSepTask not implemented")
}
func (UnimplementedAudioSepTaskServiceServer) UploadStemsURLs(context.Context, *UploadStemsURLsRequest) (*UploadStemsURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStemsURLs not implemented")
}
func (UnimplementedAudioSepTaskServiceServer) TryUpdate(context.Context, *TryUpdateRequest) (*TryUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TryUpdate not implemented")
}
func (UnimplementedAudioSepTaskServiceServer) mustEmbedUnimplementedAudioSepTaskServiceServer() {}
func (UnimplementedAudioSepTaskServiceServer) testEmbeddedByValue()                             {}

// UnsafeAudioSepTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioSepTaskServiceServer will
// result in compilation errors.
type UnsafeAudioSepTaskServiceServer interface {
	mustEmbedUnimplementedAudioSepTaskServiceServer()
}

func RegisterAudioSepTaskServiceServer(s grpc.ServiceRegistrar, srv AudioSepTaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedAudioSepTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioSepTaskService_ServiceDesc, srv)
}

func _AudioSepTaskService_PostAudioSepTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAudioSepTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioSepTaskServiceServer).PostAudioSepTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioSepTaskService_PostAudioSepTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioSepTaskServiceServer).PostAudioSepTask(ctx, req.(*PostAudioSepTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioSepTaskService_GetAudioSepTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioSepTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioSepTaskServiceServer).GetAudioSepTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioSepTaskService_GetAudioSepTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioSepTaskServiceServer).GetAudioSepTask(ctx, req.(*GetAudioSepTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioSepTaskService_UploadStemsURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStemsURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioSepTaskServiceServer).UploadStemsURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioSepTaskService_UploadStemsURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioSepTaskServiceServer).UploadStemsURLs(ctx, req.(*UploadStemsURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioSepTaskService_TryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioSepTaskServiceServer).TryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioSepTaskService_TryUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioSepTaskServiceServer).TryUpdate(ctx, req.(*TryUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioSepTaskService_ServiceDesc is the grpc.ServiceDesc for AudioSepTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioSepTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio_sep.AudioSepTaskService",
	HandlerType: (*AudioSepTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostAudioSepTask",
			Handler:    _AudioSepTaskService_PostAudioSepTask_Handler,
		},
		{
			MethodName: "GetAudioSepTask",
			Handler:    _AudioSepTaskService_GetAudioSepTask_Handler,
		},
		{
			MethodName: "UploadStemsURLs",
			Handler:    _AudioSepTaskService_UploadStemsURLs_Handler,
		},
		{
			MethodName: "TryUpdate",
			Handler:    _AudioSepTaskService_TryUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio_separation.proto",
}
