// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tab.proto

package tab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawTab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTab) Reset() {
	*x = RawTab{}
	mi := &file_tab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTab) ProtoMessage() {}

func (x *RawTab) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTab.ProtoReflect.Descriptor instead.
func (*RawTab) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{0}
}

func (x *RawTab) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawTab) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RawTab) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Tab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,4,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tab) Reset() {
	*x = Tab{}
	mi := &file_tab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tab) ProtoMessage() {}

func (x *Tab) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tab.ProtoReflect.Descriptor instead.
func (*Tab) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{1}
}

func (x *Tab) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tab) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tab) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Tab) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type SaveTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTabRequest) Reset() {
	*x = SaveTabRequest{}
	mi := &file_tab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTabRequest) ProtoMessage() {}

func (x *SaveTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTabRequest.ProtoReflect.Descriptor instead.
func (*SaveTabRequest) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{2}
}

func (x *SaveTabRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveTabRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SaveTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTabResponse) Reset() {
	*x = SaveTabResponse{}
	mi := &file_tab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTabResponse) ProtoMessage() {}

func (x *SaveTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTabResponse.ProtoReflect.Descriptor instead.
func (*SaveTabResponse) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{3}
}

func (x *SaveTabResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTabRequest) Reset() {
	*x = DeleteTabRequest{}
	mi := &file_tab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTabRequest) ProtoMessage() {}

func (x *DeleteTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTabRequest.ProtoReflect.Descriptor instead.
func (*DeleteTabRequest) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTabRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTabResponse) Reset() {
	*x = DeleteTabResponse{}
	mi := &file_tab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTabResponse) ProtoMessage() {}

func (x *DeleteTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTabResponse.ProtoReflect.Descriptor instead.
func (*DeleteTabResponse) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{5}
}

type GetTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTabRequest) Reset() {
	*x = GetTabRequest{}
	mi := &file_tab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabRequest) ProtoMessage() {}

func (x *GetTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabRequest.ProtoReflect.Descriptor instead.
func (*GetTabRequest) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{6}
}

func (x *GetTabRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tab           *Tab                   `protobuf:"bytes,1,opt,name=tab,proto3" json:"tab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTabResponse) Reset() {
	*x = GetTabResponse{}
	mi := &file_tab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabResponse) ProtoMessage() {}

func (x *GetTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabResponse.ProtoReflect.Descriptor instead.
func (*GetTabResponse) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{7}
}

func (x *GetTabResponse) GetTab() *Tab {
	if x != nil {
		return x.Tab
	}
	return nil
}

type SearchTabsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameQuery     string                 `protobuf:"bytes,1,opt,name=name_query,json=nameQuery,proto3" json:"name_query,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTabsRequest) Reset() {
	*x = SearchTabsRequest{}
	mi := &file_tab_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTabsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTabsRequest) ProtoMessage() {}

func (x *SearchTabsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTabsRequest.ProtoReflect.Descriptor instead.
func (*SearchTabsRequest) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{8}
}

func (x *SearchTabsRequest) GetNameQuery() string {
	if x != nil {
		return x.NameQuery
	}
	return ""
}

func (x *SearchTabsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchTabsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchTabsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tabs          []*RawTab              `protobuf:"bytes,1,rep,name=tabs,proto3" json:"tabs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTabsResponse) Reset() {
	*x = SearchTabsResponse{}
	mi := &file_tab_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTabsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTabsResponse) ProtoMessage() {}

func (x *SearchTabsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTabsResponse.ProtoReflect.Descriptor instead.
func (*SearchTabsResponse) Descriptor() ([]byte, []int) {
	return file_tab_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTabsResponse) GetTabs() []*RawTab {
	if x != nil {
		return x.Tabs
	}
	return nil
}

var File_tab_proto protoreflect.FileDescriptor

const file_tab_proto_rawDesc = "" +
	"\n" +
	"\ttab.proto\x12\x03tab\"@\n" +
	"\x06RawTab\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"b\n" +
	"\x03Tab\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12#\n" +
	"\rpresigned_url\x18\x04 \x01(\tR\fpresignedUrl\"8\n" +
	"\x0eSaveTabRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"!\n" +
	"\x0fSaveTabResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10DeleteTabRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11DeleteTabResponse\"\x1f\n" +
	"\rGetTabRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0eGetTabResponse\x12\x1a\n" +
	"\x03tab\x18\x01 \x01(\v2\b.tab.TabR\x03tab\"`\n" +
	"\x11SearchTabsRequest\x12\x1d\n" +
	"\n" +
	"name_query\x18\x01 \x01(\tR\tnameQuery\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"5\n" +
	"\x12SearchTabsResponse\x12\x1f\n" +
	"\x04tabs\x18\x01 \x03(\v2\v.tab.RawTabR\x04tabs2\xf0\x01\n" +
	"\n" +
	"TabService\x124\n" +
	"\aSaveTab\x12\x13.tab.SaveTabRequest\x1a\x14.tab.SaveTabResponse\x12:\n" +
	"\tDeleteTab\x12\x15.tab.DeleteTabRequest\x1a\x16.tab.DeleteTabResponse\x121\n" +
	"\x06GetTab\x12\x12.tab.GetTabRequest\x1a\x13.tab.GetTabResponse\x12=\n" +
	"\n" +
	"SearchTabs\x12\x16.tab.SearchTabsRequest\x1a\x17.tab.SearchTabsResponseB\x06Z\x04/tabb\x06proto3"

var (
	file_tab_proto_rawDescOnce sync.Once
	file_tab_proto_rawDescData []byte
)

func file_tab_proto_rawDescGZIP() []byte {
	file_tab_proto_rawDescOnce.Do(func() {
		file_tab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tab_proto_rawDesc), len(file_tab_proto_rawDesc)))
	})
	return file_tab_proto_rawDescData
}

var file_tab_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tab_proto_goTypes = []any{
	(*RawTab)(nil),             // 0: tab.RawTab
	(*Tab)(nil),                // 1: tab.Tab
	(*SaveTabRequest)(nil),     // 2: tab.SaveTabRequest
	(*SaveTabResponse)(nil),    // 3: tab.SaveTabResponse
	(*DeleteTabRequest)(nil),   // 4: tab.DeleteTabRequest
	(*DeleteTabResponse)(nil),  // 5: tab.DeleteTabResponse
	(*GetTabRequest)(nil),      // 6: tab.GetTabRequest
	(*GetTabResponse)(nil),     // 7: tab.GetTabResponse
	(*SearchTabsRequest)(nil),  // 8: tab.SearchTabsRequest
	(*SearchTabsResponse)(nil), // 9: tab.SearchTabsResponse
}
var file_tab_proto_depIdxs = []int32{
	1, // 0: tab.GetTabResponse.tab:type_name -> tab.Tab
	0, // 1: tab.SearchTabsResponse.tabs:type_name -> tab.RawTab
	2, // 2: tab.TabService.SaveTab:input_type -> tab.SaveTabRequest
	4, // 3: tab.TabService.DeleteTab:input_type -> tab.DeleteTabRequest
	6, // 4: tab.TabService.GetTab:input_type -> tab.GetTabRequest
	8, // 5: tab.TabService.SearchTabs:input_type -> tab.SearchTabsRequest
	3, // 6: tab.TabService.SaveTab:output_type -> tab.SaveTabResponse
	5, // 7: tab.TabService.DeleteTab:output_type -> tab.DeleteTabResponse
	7, // 8: tab.TabService.GetTab:output_type -> tab.GetTabResponse
	9, // 9: tab.TabService.SearchTabs:output_type -> tab.SearchTabsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tab_proto_init() }
func file_tab_proto_init() {
	if File_tab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tab_proto_rawDesc), len(file_tab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tab_proto_goTypes,
		DependencyIndexes: file_tab_proto_depIdxs,
		MessageInfos:      file_tab_proto_msgTypes,
	}.Build()
	File_tab_proto = out.File
	file_tab_proto_goTypes = nil
	file_tab_proto_depIdxs = nil
}
