// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: tab.proto

package tab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TabService_SaveTab_FullMethodName          = "/tab.TabService/SaveTab"
	TabService_DeleteTab_FullMethodName        = "/tab.TabService/DeleteTab"
	TabService_GetTab_FullMethodName           = "/tab.TabService/GetTab"
	TabService_SearchTabsByName_FullMethodName = "/tab.TabService/SearchTabsByName"
)

// TabServiceClient is the client API for TabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tab service
type TabServiceClient interface {
	// SaveTab saves a tab to the database (when file already exists in storage)
	SaveTab(ctx context.Context, in *SaveTabRequest, opts ...grpc.CallOption) (*CreateTabResponse, error)
	// DeleteTab deletes a tab from the database and storage
	DeleteTab(ctx context.Context, in *DeleteTabRequest, opts ...grpc.CallOption) (*DeleteTabResponse, error)
	// GetTab gets a tab from the database with presigned url to file in storage
	GetTab(ctx context.Context, in *GetTabRequest, opts ...grpc.CallOption) (*GetTabResponse, error)
	// SearchTabsByName searches tabs by query and returns a list of tabs without presigned url
	SearchTabsByName(ctx context.Context, in *SearchTabsRequest, opts ...grpc.CallOption) (*SearchTabsResponse, error)
}

type tabServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTabServiceClient(cc grpc.ClientConnInterface) TabServiceClient {
	return &tabServiceClient{cc}
}

func (c *tabServiceClient) SaveTab(ctx context.Context, in *SaveTabRequest, opts ...grpc.CallOption) (*CreateTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTabResponse)
	err := c.cc.Invoke(ctx, TabService_SaveTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabServiceClient) DeleteTab(ctx context.Context, in *DeleteTabRequest, opts ...grpc.CallOption) (*DeleteTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTabResponse)
	err := c.cc.Invoke(ctx, TabService_DeleteTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabServiceClient) GetTab(ctx context.Context, in *GetTabRequest, opts ...grpc.CallOption) (*GetTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTabResponse)
	err := c.cc.Invoke(ctx, TabService_GetTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabServiceClient) SearchTabsByName(ctx context.Context, in *SearchTabsRequest, opts ...grpc.CallOption) (*SearchTabsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTabsResponse)
	err := c.cc.Invoke(ctx, TabService_SearchTabsByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TabServiceServer is the server API for TabService service.
// All implementations must embed UnimplementedTabServiceServer
// for forward compatibility.
//
// Tab service
type TabServiceServer interface {
	// SaveTab saves a tab to the database (when file already exists in storage)
	SaveTab(context.Context, *SaveTabRequest) (*CreateTabResponse, error)
	// DeleteTab deletes a tab from the database and storage
	DeleteTab(context.Context, *DeleteTabRequest) (*DeleteTabResponse, error)
	// GetTab gets a tab from the database with presigned url to file in storage
	GetTab(context.Context, *GetTabRequest) (*GetTabResponse, error)
	// SearchTabsByName searches tabs by query and returns a list of tabs without presigned url
	SearchTabsByName(context.Context, *SearchTabsRequest) (*SearchTabsResponse, error)
	mustEmbedUnimplementedTabServiceServer()
}

// UnimplementedTabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTabServiceServer struct{}

func (UnimplementedTabServiceServer) SaveTab(context.Context, *SaveTabRequest) (*CreateTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTab not implemented")
}
func (UnimplementedTabServiceServer) DeleteTab(context.Context, *DeleteTabRequest) (*DeleteTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTab not implemented")
}
func (UnimplementedTabServiceServer) GetTab(context.Context, *GetTabRequest) (*GetTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTab not implemented")
}
func (UnimplementedTabServiceServer) SearchTabsByName(context.Context, *SearchTabsRequest) (*SearchTabsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTabsByName not implemented")
}
func (UnimplementedTabServiceServer) mustEmbedUnimplementedTabServiceServer() {}
func (UnimplementedTabServiceServer) testEmbeddedByValue()                    {}

// UnsafeTabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TabServiceServer will
// result in compilation errors.
type UnsafeTabServiceServer interface {
	mustEmbedUnimplementedTabServiceServer()
}

func RegisterTabServiceServer(s grpc.ServiceRegistrar, srv TabServiceServer) {
	// If the following call pancis, it indicates UnimplementedTabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TabService_ServiceDesc, srv)
}

func _TabService_SaveTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabServiceServer).SaveTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabService_SaveTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabServiceServer).SaveTab(ctx, req.(*SaveTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabService_DeleteTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabServiceServer).DeleteTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabService_DeleteTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabServiceServer).DeleteTab(ctx, req.(*DeleteTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabService_GetTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabServiceServer).GetTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabService_GetTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabServiceServer).GetTab(ctx, req.(*GetTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabService_SearchTabsByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabServiceServer).SearchTabsByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabService_SearchTabsByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabServiceServer).SearchTabsByName(ctx, req.(*SearchTabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TabService_ServiceDesc is the grpc.ServiceDesc for TabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tab.TabService",
	HandlerType: (*TabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTab",
			Handler:    _TabService_SaveTab_Handler,
		},
		{
			MethodName: "DeleteTab",
			Handler:    _TabService_DeleteTab_Handler,
		},
		{
			MethodName: "GetTab",
			Handler:    _TabService_GetTab_Handler,
		},
		{
			MethodName: "SearchTabsByName",
			Handler:    _TabService_SearchTabsByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tab.proto",
}
