// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: tab_generation.proto

package tabgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_CREATED                Status = 0
	Status_PENDING                Status = 1
	Status_WAITING_FOR_SEPARATION Status = 2
	Status_PROCESSING             Status = 3
	Status_DONE                   Status = 4
	Status_FAILED                 Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "CREATED",
		1: "PENDING",
		2: "WAITING_FOR_SEPARATION",
		3: "PROCESSING",
		4: "DONE",
		5: "FAILED",
	}
	Status_value = map[string]int32{
		"CREATED":                0,
		"PENDING":                1,
		"WAITING_FOR_SEPARATION": 2,
		"PROCESSING":             3,
		"DONE":                   4,
		"FAILED":                 5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tab_generation_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tab_generation_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{0}
}

type TabGenTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AudioSepTaskId *string                `protobuf:"bytes,2,opt,name=audio_sep_task_id,json=audioSepTaskId,proto3,oneof" json:"audio_sep_task_id,omitempty"`
	Status         Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=tabgen.Status" json:"status,omitempty"`
	InputAudioName string                 `protobuf:"bytes,4,opt,name=input_audio_name,json=inputAudioName,proto3" json:"input_audio_name,omitempty"`
	ResultTabName  *string                `protobuf:"bytes,5,opt,name=result_tab_name,json=resultTabName,proto3,oneof" json:"result_tab_name,omitempty"`
	Saved          bool                   `protobuf:"varint,6,opt,name=saved,proto3" json:"saved,omitempty"`
	ErrorMessage   *string                `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TabGenTask) Reset() {
	*x = TabGenTask{}
	mi := &file_tab_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabGenTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabGenTask) ProtoMessage() {}

func (x *TabGenTask) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabGenTask.ProtoReflect.Descriptor instead.
func (*TabGenTask) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{0}
}

func (x *TabGenTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TabGenTask) GetAudioSepTaskId() string {
	if x != nil && x.AudioSepTaskId != nil {
		return *x.AudioSepTaskId
	}
	return ""
}

func (x *TabGenTask) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_CREATED
}

func (x *TabGenTask) GetInputAudioName() string {
	if x != nil {
		return x.InputAudioName
	}
	return ""
}

func (x *TabGenTask) GetResultTabName() string {
	if x != nil && x.ResultTabName != nil {
		return *x.ResultTabName
	}
	return ""
}

func (x *TabGenTask) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

func (x *TabGenTask) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_tab_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PostTabGenTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         *File                  `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Separation    bool                   `protobuf:"varint,2,opt,name=separation,proto3" json:"separation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTabGenTaskRequest) Reset() {
	*x = PostTabGenTaskRequest{}
	mi := &file_tab_generation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTabGenTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTabGenTaskRequest) ProtoMessage() {}

func (x *PostTabGenTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTabGenTaskRequest.ProtoReflect.Descriptor instead.
func (*PostTabGenTaskRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{2}
}

func (x *PostTabGenTaskRequest) GetAudio() *File {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *PostTabGenTaskRequest) GetSeparation() bool {
	if x != nil {
		return x.Separation
	}
	return false
}

type PostTabGenTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TabGenTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTabGenTaskResponse) Reset() {
	*x = PostTabGenTaskResponse{}
	mi := &file_tab_generation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTabGenTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTabGenTaskResponse) ProtoMessage() {}

func (x *PostTabGenTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTabGenTaskResponse.ProtoReflect.Descriptor instead.
func (*PostTabGenTaskResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{3}
}

func (x *PostTabGenTaskResponse) GetTask() *TabGenTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTabGenTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTabGenTaskRequest) Reset() {
	*x = GetTabGenTaskRequest{}
	mi := &file_tab_generation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabGenTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabGenTaskRequest) ProtoMessage() {}

func (x *GetTabGenTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabGenTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTabGenTaskRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{4}
}

func (x *GetTabGenTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTabGenTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TabGenTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	TabUrl        *string                `protobuf:"bytes,2,opt,name=tab_url,json=tabUrl,proto3,oneof" json:"tab_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTabGenTaskResponse) Reset() {
	*x = GetTabGenTaskResponse{}
	mi := &file_tab_generation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabGenTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabGenTaskResponse) ProtoMessage() {}

func (x *GetTabGenTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabGenTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTabGenTaskResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{5}
}

func (x *GetTabGenTaskResponse) GetTask() *TabGenTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTabGenTaskResponse) GetTabUrl() string {
	if x != nil && x.TabUrl != nil {
		return *x.TabUrl
	}
	return ""
}

type SaveTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTabRequest) Reset() {
	*x = SaveTabRequest{}
	mi := &file_tab_generation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTabRequest) ProtoMessage() {}

func (x *SaveTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTabRequest.ProtoReflect.Descriptor instead.
func (*SaveTabRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{6}
}

func (x *SaveTabRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveTabRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SaveTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTabResponse) Reset() {
	*x = SaveTabResponse{}
	mi := &file_tab_generation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTabResponse) ProtoMessage() {}

func (x *SaveTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTabResponse.ProtoReflect.Descriptor instead.
func (*SaveTabResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{7}
}

type TryUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Froms         []Status               `protobuf:"varint,2,rep,packed,name=froms,proto3,enum=tabgen.Status" json:"froms,omitempty"`
	To            Status                 `protobuf:"varint,3,opt,name=to,proto3,enum=tabgen.Status" json:"to,omitempty"`
	ResultTabName *string                `protobuf:"bytes,4,opt,name=result_tab_name,json=resultTabName,proto3,oneof" json:"result_tab_name,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryUpdateRequest) Reset() {
	*x = TryUpdateRequest{}
	mi := &file_tab_generation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUpdateRequest) ProtoMessage() {}

func (x *TryUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUpdateRequest.ProtoReflect.Descriptor instead.
func (*TryUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{8}
}

func (x *TryUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TryUpdateRequest) GetFroms() []Status {
	if x != nil {
		return x.Froms
	}
	return nil
}

func (x *TryUpdateRequest) GetTo() Status {
	if x != nil {
		return x.To
	}
	return Status_CREATED
}

func (x *TryUpdateRequest) GetResultTabName() string {
	if x != nil && x.ResultTabName != nil {
		return *x.ResultTabName
	}
	return ""
}

func (x *TryUpdateRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type TryUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryUpdateResponse) Reset() {
	*x = TryUpdateResponse{}
	mi := &file_tab_generation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUpdateResponse) ProtoMessage() {}

func (x *TryUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUpdateResponse.ProtoReflect.Descriptor instead.
func (*TryUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{9}
}

func (x *TryUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAudioSourceURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioSourceURLRequest) Reset() {
	*x = GetAudioSourceURLRequest{}
	mi := &file_tab_generation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioSourceURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioSourceURLRequest) ProtoMessage() {}

func (x *GetAudioSourceURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioSourceURLRequest.ProtoReflect.Descriptor instead.
func (*GetAudioSourceURLRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{10}
}

func (x *GetAudioSourceURLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAudioSourceURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioSourceURLResponse) Reset() {
	*x = GetAudioSourceURLResponse{}
	mi := &file_tab_generation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioSourceURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioSourceURLResponse) ProtoMessage() {}

func (x *GetAudioSourceURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioSourceURLResponse.ProtoReflect.Descriptor instead.
func (*GetAudioSourceURLResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{11}
}

func (x *GetAudioSourceURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tab           *File                  `protobuf:"bytes,2,opt,name=tab,proto3" json:"tab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTabRequest) Reset() {
	*x = UploadTabRequest{}
	mi := &file_tab_generation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTabRequest) ProtoMessage() {}

func (x *UploadTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTabRequest.ProtoReflect.Descriptor instead.
func (*UploadTabRequest) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{12}
}

func (x *UploadTabRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadTabRequest) GetTab() *File {
	if x != nil {
		return x.Tab
	}
	return nil
}

type UploadTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTabResponse) Reset() {
	*x = UploadTabResponse{}
	mi := &file_tab_generation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTabResponse) ProtoMessage() {}

func (x *UploadTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tab_generation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTabResponse.ProtoReflect.Descriptor instead.
func (*UploadTabResponse) Descriptor() ([]byte, []int) {
	return file_tab_generation_proto_rawDescGZIP(), []int{13}
}

var File_tab_generation_proto protoreflect.FileDescriptor

const file_tab_generation_proto_rawDesc = "" +
	"\n" +
	"\x14tab_generation.proto\x12\x06tabgen\"\xc7\x02\n" +
	"\n" +
	"TabGenTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x11audio_sep_task_id\x18\x02 \x01(\tH\x00R\x0eaudioSepTaskId\x88\x01\x01\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.tabgen.StatusR\x06status\x12(\n" +
	"\x10input_audio_name\x18\x04 \x01(\tR\x0einputAudioName\x12+\n" +
	"\x0fresult_tab_name\x18\x05 \x01(\tH\x01R\rresultTabName\x88\x01\x01\x12\x14\n" +
	"\x05saved\x18\x06 \x01(\bR\x05saved\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x02R\ferrorMessage\x88\x01\x01B\x14\n" +
	"\x12_audio_sep_task_idB\x12\n" +
	"\x10_result_tab_nameB\x10\n" +
	"\x0e_error_message\"B\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"[\n" +
	"\x15PostTabGenTaskRequest\x12\"\n" +
	"\x05audio\x18\x01 \x01(\v2\f.tabgen.FileR\x05audio\x12\x1e\n" +
	"\n" +
	"separation\x18\x02 \x01(\bR\n" +
	"separation\"@\n" +
	"\x16PostTabGenTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.tabgen.TabGenTaskR\x04task\"&\n" +
	"\x14GetTabGenTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x15GetTabGenTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.tabgen.TabGenTaskR\x04task\x12\x1c\n" +
	"\atab_url\x18\x02 \x01(\tH\x00R\x06tabUrl\x88\x01\x01B\n" +
	"\n" +
	"\b_tab_url\"4\n" +
	"\x0eSaveTabRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x11\n" +
	"\x0fSaveTabResponse\"\xe5\x01\n" +
	"\x10TryUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x05froms\x18\x02 \x03(\x0e2\x0e.tabgen.StatusR\x05froms\x12\x1e\n" +
	"\x02to\x18\x03 \x01(\x0e2\x0e.tabgen.StatusR\x02to\x12+\n" +
	"\x0fresult_tab_name\x18\x04 \x01(\tH\x00R\rresultTabName\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\x12\n" +
	"\x10_result_tab_nameB\x10\n" +
	"\x0e_error_message\"-\n" +
	"\x11TryUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x18GetAudioSourceURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x19GetAudioSourceURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"B\n" +
	"\x10UploadTabRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x03tab\x18\x02 \x01(\v2\f.tabgen.FileR\x03tab\"\x13\n" +
	"\x11UploadTabResponse*d\n" +
	"\x06Status\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x1a\n" +
	"\x16WAITING_FOR_SEPARATION\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\b\n" +
	"\x04DONE\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x052\xcc\x03\n" +
	"\x11TabGenTaskService\x12O\n" +
	"\x0ePostTabGenTask\x12\x1d.tabgen.PostTabGenTaskRequest\x1a\x1e.tabgen.PostTabGenTaskResponse\x12L\n" +
	"\rGetTabGenTask\x12\x1c.tabgen.GetTabGenTaskRequest\x1a\x1d.tabgen.GetTabGenTaskResponse\x12:\n" +
	"\aSaveTab\x12\x16.tabgen.SaveTabRequest\x1a\x17.tabgen.SaveTabResponse\x12@\n" +
	"\tTryUpdate\x12\x18.tabgen.TryUpdateRequest\x1a\x19.tabgen.TryUpdateResponse\x12X\n" +
	"\x11GetAudioSourceURL\x12 .tabgen.GetAudioSourceURLRequest\x1a!.tabgen.GetAudioSourceURLResponse\x12@\n" +
	"\tUploadTab\x12\x18.tabgen.UploadTabRequest\x1a\x19.tabgen.UploadTabResponseB\tZ\a/tabgenb\x06proto3"

var (
	file_tab_generation_proto_rawDescOnce sync.Once
	file_tab_generation_proto_rawDescData []byte
)

func file_tab_generation_proto_rawDescGZIP() []byte {
	file_tab_generation_proto_rawDescOnce.Do(func() {
		file_tab_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tab_generation_proto_rawDesc), len(file_tab_generation_proto_rawDesc)))
	})
	return file_tab_generation_proto_rawDescData
}

var file_tab_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tab_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tab_generation_proto_goTypes = []any{
	(Status)(0),                       // 0: tabgen.Status
	(*TabGenTask)(nil),                // 1: tabgen.TabGenTask
	(*File)(nil),                      // 2: tabgen.File
	(*PostTabGenTaskRequest)(nil),     // 3: tabgen.PostTabGenTaskRequest
	(*PostTabGenTaskResponse)(nil),    // 4: tabgen.PostTabGenTaskResponse
	(*GetTabGenTaskRequest)(nil),      // 5: tabgen.GetTabGenTaskRequest
	(*GetTabGenTaskResponse)(nil),     // 6: tabgen.GetTabGenTaskResponse
	(*SaveTabRequest)(nil),            // 7: tabgen.SaveTabRequest
	(*SaveTabResponse)(nil),           // 8: tabgen.SaveTabResponse
	(*TryUpdateRequest)(nil),          // 9: tabgen.TryUpdateRequest
	(*TryUpdateResponse)(nil),         // 10: tabgen.TryUpdateResponse
	(*GetAudioSourceURLRequest)(nil),  // 11: tabgen.GetAudioSourceURLRequest
	(*GetAudioSourceURLResponse)(nil), // 12: tabgen.GetAudioSourceURLResponse
	(*UploadTabRequest)(nil),          // 13: tabgen.UploadTabRequest
	(*UploadTabResponse)(nil),         // 14: tabgen.UploadTabResponse
}
var file_tab_generation_proto_depIdxs = []int32{
	0,  // 0: tabgen.TabGenTask.status:type_name -> tabgen.Status
	2,  // 1: tabgen.PostTabGenTaskRequest.audio:type_name -> tabgen.File
	1,  // 2: tabgen.PostTabGenTaskResponse.task:type_name -> tabgen.TabGenTask
	1,  // 3: tabgen.GetTabGenTaskResponse.task:type_name -> tabgen.TabGenTask
	0,  // 4: tabgen.TryUpdateRequest.froms:type_name -> tabgen.Status
	0,  // 5: tabgen.TryUpdateRequest.to:type_name -> tabgen.Status
	2,  // 6: tabgen.UploadTabRequest.tab:type_name -> tabgen.File
	3,  // 7: tabgen.TabGenTaskService.PostTabGenTask:input_type -> tabgen.PostTabGenTaskRequest
	5,  // 8: tabgen.TabGenTaskService.GetTabGenTask:input_type -> tabgen.GetTabGenTaskRequest
	7,  // 9: tabgen.TabGenTaskService.SaveTab:input_type -> tabgen.SaveTabRequest
	9,  // 10: tabgen.TabGenTaskService.TryUpdate:input_type -> tabgen.TryUpdateRequest
	11, // 11: tabgen.TabGenTaskService.GetAudioSourceURL:input_type -> tabgen.GetAudioSourceURLRequest
	13, // 12: tabgen.TabGenTaskService.UploadTab:input_type -> tabgen.UploadTabRequest
	4,  // 13: tabgen.TabGenTaskService.PostTabGenTask:output_type -> tabgen.PostTabGenTaskResponse
	6,  // 14: tabgen.TabGenTaskService.GetTabGenTask:output_type -> tabgen.GetTabGenTaskResponse
	8,  // 15: tabgen.TabGenTaskService.SaveTab:output_type -> tabgen.SaveTabResponse
	10, // 16: tabgen.TabGenTaskService.TryUpdate:output_type -> tabgen.TryUpdateResponse
	12, // 17: tabgen.TabGenTaskService.GetAudioSourceURL:output_type -> tabgen.GetAudioSourceURLResponse
	14, // 18: tabgen.TabGenTaskService.UploadTab:output_type -> tabgen.UploadTabResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tab_generation_proto_init() }
func file_tab_generation_proto_init() {
	if File_tab_generation_proto != nil {
		return
	}
	file_tab_generation_proto_msgTypes[0].OneofWrappers = []any{}
	file_tab_generation_proto_msgTypes[5].OneofWrappers = []any{}
	file_tab_generation_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tab_generation_proto_rawDesc), len(file_tab_generation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tab_generation_proto_goTypes,
		DependencyIndexes: file_tab_generation_proto_depIdxs,
		EnumInfos:         file_tab_generation_proto_enumTypes,
		MessageInfos:      file_tab_generation_proto_msgTypes,
	}.Build()
	File_tab_generation_proto = out.File
	file_tab_generation_proto_goTypes = nil
	file_tab_generation_proto_depIdxs = nil
}
