// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: tab_generation.proto

package tabgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TabGenTaskService_PostTabGenTask_FullMethodName    = "/tabgen.TabGenTaskService/PostTabGenTask"
	TabGenTaskService_GetTabGenTask_FullMethodName     = "/tabgen.TabGenTaskService/GetTabGenTask"
	TabGenTaskService_SaveTab_FullMethodName           = "/tabgen.TabGenTaskService/SaveTab"
	TabGenTaskService_TryUpdate_FullMethodName         = "/tabgen.TabGenTaskService/TryUpdate"
	TabGenTaskService_GetAudioSourceURL_FullMethodName = "/tabgen.TabGenTaskService/GetAudioSourceURL"
	TabGenTaskService_UploadTab_FullMethodName         = "/tabgen.TabGenTaskService/UploadTab"
)

// TabGenTaskServiceClient is the client API for TabGenTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TabGenTaskService is a service for generating tablature tasks.
type TabGenTaskServiceClient interface {
	// Creates tab generation task and posts it to queue broker. Returns task id.
	PostTabGenTask(ctx context.Context, in *PostTabGenTaskRequest, opts ...grpc.CallOption) (*PostTabGenTaskResponse, error)
	// Returns tab generation task by id. If tab is ready, returns tab URL.
	GetTabGenTask(ctx context.Context, in *GetTabGenTaskRequest, opts ...grpc.CallOption) (*GetTabGenTaskResponse, error)
	// Saves generated tab to storage
	SaveTab(ctx context.Context, in *SaveTabRequest, opts ...grpc.CallOption) (*SaveTabResponse, error)
	// Try to update task status
	TryUpdate(ctx context.Context, in *TryUpdateRequest, opts ...grpc.CallOption) (*TryUpdateResponse, error)
	// Return presigned URL for audio source
	GetAudioSourceURL(ctx context.Context, in *GetAudioSourceURLRequest, opts ...grpc.CallOption) (*GetAudioSourceURLResponse, error)
	// Uploads tab to storage
	UploadTab(ctx context.Context, in *UploadTabRequest, opts ...grpc.CallOption) (*UploadTabResponse, error)
}

type tabGenTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTabGenTaskServiceClient(cc grpc.ClientConnInterface) TabGenTaskServiceClient {
	return &tabGenTaskServiceClient{cc}
}

func (c *tabGenTaskServiceClient) PostTabGenTask(ctx context.Context, in *PostTabGenTaskRequest, opts ...grpc.CallOption) (*PostTabGenTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostTabGenTaskResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_PostTabGenTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabGenTaskServiceClient) GetTabGenTask(ctx context.Context, in *GetTabGenTaskRequest, opts ...grpc.CallOption) (*GetTabGenTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTabGenTaskResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_GetTabGenTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabGenTaskServiceClient) SaveTab(ctx context.Context, in *SaveTabRequest, opts ...grpc.CallOption) (*SaveTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTabResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_SaveTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabGenTaskServiceClient) TryUpdate(ctx context.Context, in *TryUpdateRequest, opts ...grpc.CallOption) (*TryUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryUpdateResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_TryUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabGenTaskServiceClient) GetAudioSourceURL(ctx context.Context, in *GetAudioSourceURLRequest, opts ...grpc.CallOption) (*GetAudioSourceURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudioSourceURLResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_GetAudioSourceURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabGenTaskServiceClient) UploadTab(ctx context.Context, in *UploadTabRequest, opts ...grpc.CallOption) (*UploadTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTabResponse)
	err := c.cc.Invoke(ctx, TabGenTaskService_UploadTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TabGenTaskServiceServer is the server API for TabGenTaskService service.
// All implementations must embed UnimplementedTabGenTaskServiceServer
// for forward compatibility.
//
// TabGenTaskService is a service for generating tablature tasks.
type TabGenTaskServiceServer interface {
	// Creates tab generation task and posts it to queue broker. Returns task id.
	PostTabGenTask(context.Context, *PostTabGenTaskRequest) (*PostTabGenTaskResponse, error)
	// Returns tab generation task by id. If tab is ready, returns tab URL.
	GetTabGenTask(context.Context, *GetTabGenTaskRequest) (*GetTabGenTaskResponse, error)
	// Saves generated tab to storage
	SaveTab(context.Context, *SaveTabRequest) (*SaveTabResponse, error)
	// Try to update task status
	TryUpdate(context.Context, *TryUpdateRequest) (*TryUpdateResponse, error)
	// Return presigned URL for audio source
	GetAudioSourceURL(context.Context, *GetAudioSourceURLRequest) (*GetAudioSourceURLResponse, error)
	// Uploads tab to storage
	UploadTab(context.Context, *UploadTabRequest) (*UploadTabResponse, error)
	mustEmbedUnimplementedTabGenTaskServiceServer()
}

// UnimplementedTabGenTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTabGenTaskServiceServer struct{}

func (UnimplementedTabGenTaskServiceServer) PostTabGenTask(context.Context, *PostTabGenTaskRequest) (*PostTabGenTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTabGenTask not implemented")
}
func (UnimplementedTabGenTaskServiceServer) GetTabGenTask(context.Context, *GetTabGenTaskRequest) (*GetTabGenTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTabGenTask not implemented")
}
func (UnimplementedTabGenTaskServiceServer) SaveTab(context.Context, *SaveTabRequest) (*SaveTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTab not implemented")
}
func (UnimplementedTabGenTaskServiceServer) TryUpdate(context.Context, *TryUpdateRequest) (*TryUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TryUpdate not implemented")
}
func (UnimplementedTabGenTaskServiceServer) GetAudioSourceURL(context.Context, *GetAudioSourceURLRequest) (*GetAudioSourceURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioSourceURL not implemented")
}
func (UnimplementedTabGenTaskServiceServer) UploadTab(context.Context, *UploadTabRequest) (*UploadTabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadTab not implemented")
}
func (UnimplementedTabGenTaskServiceServer) mustEmbedUnimplementedTabGenTaskServiceServer() {}
func (UnimplementedTabGenTaskServiceServer) testEmbeddedByValue()                           {}

// UnsafeTabGenTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TabGenTaskServiceServer will
// result in compilation errors.
type UnsafeTabGenTaskServiceServer interface {
	mustEmbedUnimplementedTabGenTaskServiceServer()
}

func RegisterTabGenTaskServiceServer(s grpc.ServiceRegistrar, srv TabGenTaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTabGenTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TabGenTaskService_ServiceDesc, srv)
}

func _TabGenTaskService_PostTabGenTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTabGenTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).PostTabGenTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_PostTabGenTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).PostTabGenTask(ctx, req.(*PostTabGenTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabGenTaskService_GetTabGenTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabGenTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).GetTabGenTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_GetTabGenTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).GetTabGenTask(ctx, req.(*GetTabGenTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabGenTaskService_SaveTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).SaveTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_SaveTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).SaveTab(ctx, req.(*SaveTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabGenTaskService_TryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).TryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_TryUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).TryUpdate(ctx, req.(*TryUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabGenTaskService_GetAudioSourceURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioSourceURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).GetAudioSourceURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_GetAudioSourceURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).GetAudioSourceURL(ctx, req.(*GetAudioSourceURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabGenTaskService_UploadTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabGenTaskServiceServer).UploadTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabGenTaskService_UploadTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabGenTaskServiceServer).UploadTab(ctx, req.(*UploadTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TabGenTaskService_ServiceDesc is the grpc.ServiceDesc for TabGenTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TabGenTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tabgen.TabGenTaskService",
	HandlerType: (*TabGenTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostTabGenTask",
			Handler:    _TabGenTaskService_PostTabGenTask_Handler,
		},
		{
			MethodName: "GetTabGenTask",
			Handler:    _TabGenTaskService_GetTabGenTask_Handler,
		},
		{
			MethodName: "SaveTab",
			Handler:    _TabGenTaskService_SaveTab_Handler,
		},
		{
			MethodName: "TryUpdate",
			Handler:    _TabGenTaskService_TryUpdate_Handler,
		},
		{
			MethodName: "GetAudioSourceURL",
			Handler:    _TabGenTaskService_GetAudioSourceURL_Handler,
		},
		{
			MethodName: "UploadTab",
			Handler:    _TabGenTaskService_UploadTab_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tab_generation.proto",
}
